# Generated by Django 5.2.8 on 2025-12-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
